# Generated by Django 3.2.3 on 2022-05-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='users',
        ),
        migrations.AddField(
            model_name='command',
            name='user_roles',
            field=models.ManyToManyField(blank=True, to='users.UserRole', verbose_name='Роли пользователей'),
        ),
    ]
