# Generated by Django 3.0.1 on 2021-10-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='age_limit',
            field=models.CharField(default='Не указан', max_length=10),
        ),
        migrations.AddField(
            model_name='articles',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
