# Generated by Django 3.0.1 on 2022-02-12 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20211020_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='checked',
            new_name='adminchecked',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='age_limit',
            new_name='gender',
        ),
    ]
