# Generated by Django 3.0.1 on 2022-02-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20220212_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='adminchecked',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
