# Generated by Django 3.2.3 on 2022-04-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('anons', models.CharField(max_length=250, verbose_name='Анонс')),
                ('questions', models.CharField(max_length=10000, verbose_name='Вопросы')),
                ('answers', models.CharField(max_length=10000, verbose_name='Ответы')),
            ],
        ),
    ]
