# Generated by Django 3.2.3 on 2022-05-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='anons',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title',
        ),
        migrations.AddField(
            model_name='quiz',
            name='test_name',
            field=models.CharField(max_length=120, null=True, verbose_name='Название теста'),
        ),
    ]
