# Generated by Django 3.2.3 on 2022-05-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20220517_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionvariant',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='variants',
            field=models.ManyToManyField(blank=True, to='quiz.QuestionVariant', verbose_name='Варианты'),
        ),
    ]
