# Generated by Django 3.2.3 on 2022-05-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20220518_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='Диагноз')),
                ('variants', models.ManyToManyField(blank=True, to='quiz.QuestionVariant', verbose_name='Варианты')),
            ],
        ),
    ]
