# Generated by Django 3.2.3 on 2022-05-22 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_resultpattern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='description',
        ),
        migrations.AddField(
            model_name='result',
            name='pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.resultpattern', verbose_name='Паттерн'),
        ),
    ]
