# Generated by Django 3.2.3 on 2022-05-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20220522_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionvariant',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='Балл'),
        ),
        migrations.AddField(
            model_name='result',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='Балл'),
        ),
        migrations.AddField(
            model_name='resultpattern',
            name='max_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Максимальный балл'),
        ),
        migrations.AddField(
            model_name='resultpattern',
            name='min_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Минимальный балл'),
        ),
    ]
