# Generated by Django 3.2.3 on 2022-05-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20220523_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='type',
            field=models.IntegerField(choices=[(1, 'Score'), (2, 'Choices')], default=2, verbose_name='Тип теста'),
        ),
    ]
