# Generated by Django 3.2.3 on 2022-05-25 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_quiz_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultpattern',
            name='prefer_team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.resultpattern', verbose_name='Предпочитаемый тип участника команды'),
        ),
    ]
