# Generated by Django 3.2.3 on 2022-05-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_resultpattern_prefer_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionvariant',
            name='scale',
            field=models.IntegerField(blank=True, choices=[(1, 'Стабильность'), (2, 'Открытость')], null=True, verbose_name='Cтабильность - Открытость'),
        ),
        migrations.AddField(
            model_name='resultpattern',
            name='opened_score_from',
            field=models.FloatField(blank=True, null=True, verbose_name='Открытость от'),
        ),
        migrations.AddField(
            model_name='resultpattern',
            name='opened_score_to',
            field=models.FloatField(blank=True, null=True, verbose_name='Открытость до'),
        ),
        migrations.AddField(
            model_name='resultpattern',
            name='stability_score_from',
            field=models.FloatField(blank=True, null=True, verbose_name='Стабильность от'),
        ),
        migrations.AddField(
            model_name='resultpattern',
            name='stability_score_to',
            field=models.FloatField(blank=True, null=True, verbose_name='Стабильность до'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='type',
            field=models.IntegerField(choices=[(1, 'Score'), (2, 'Choices'), (3, 'Temperament')], default=2, verbose_name='Тип теста'),
        ),
    ]
