# Generated by Django 3.0.1 on 2019-12-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ous', '0002_auto_20191227_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SecondName', models.TextField()),
                ('FirstName', models.TextField()),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
